### ISSUE TITLE
[Race][Background] Racial background wrongly applied to pawn of other races

### ISSUE THREAD

**Issue by TyrantProd** [neronix17/-O21-Outer-Rim-Core#6]
**Current Behaviour**
A pawn was given as quest reward, he had the T-series droid background but his race was human.
**Repro Steps**
*Rate 1/2*

1. Obtain a Quest that rewards characters with background from Outer-Rim-Core
2. Complete the quest
3. Compare the rewarded character's background to his race

**Notes**

- Issue was found trough natural gameplay
- Repro rate might be higher as this was only observed for two different quests
- Please view attached screenshot for further details
![021-issue_6](https://user-images.githubusercontent.com/62632833/77498235-8d330d80-6e25-11ea-8a05-624777dd4aff.jpg)

**Comment by neronix17** [comment]
Not my problem to fix. It's either vanillas broken as fuck refugee system or an issue for Humand Alien Races to handle, since it's HAR that adds the option of custom backstories at all.
